fun main() {
    println("Hello Project Euler")
//    Problem 1 call
    multiplesOf3And5()
//    Problem 2 call
    evenFibonacciNumbers()

}


/**
 * Problem 1: If we list all the natural numbers below 10 that are multiples of 3 or 5,
 * we get 3, 5, 6 and 9. The sum of these multiples is 23.
 * Find the sum of all the multiples of 3 or 5 below 1000. Answer : 233168
 * */

fun multiplesOf3And5() {
    println("***************** Problem 1 ******************")
    val maxNumber = 1000
    var result = 0
    for (i in 0 until maxNumber) {
        if (i % 3 == 0 || i % 5 == 0) result += i
    }
    println("Sum of all the multiples of 3 or 5 below $maxNumber is $result")
}

/**
 * Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * */

fun evenFibonacciNumbers() {
    println("***************** Problem 2 ******************")
    val maxNumber = 4_000_000
    var t1 = 0
    var t2 = 1
    var sum = 0
    var evenSum = 0

    while (sum < maxNumber){
        sum = t1 + t2
        t1 = t2
        t2 = sum
        if (t2 %2 == 0) evenSum += sum
    }
    println("Sum of the even-valued terms is $evenSum")
}